jupyter_book_task:
  env:
    JULIA_NUM_THREADS: 2
  auto_cancellation: true
  container:
    image: ghcr.io/sosiristseng/docker-juliabook:1.7.3.12
    cpu: 2
    memory: 8G
    use_in_memory_disk: true
  julia_cache:
    folder: ~/.julia
    fingerprint_script: cat Manifest.toml
  package_script: |
    julia --threads=auto --color=yes --project=@. -e 'import Pkg; Pkg.instantiate()'
  build_script: |
    jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace index.ipynb
    mkdir out && cp index.ipynb out/

  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n out/
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
